apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
  namespace: food-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
      - name: order-db
        image: postgres:14
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: order-db-credentials
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: order-db-credentials
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: order-db-credentials
                key: POSTGRES_DB
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: order-db-storage
      volumes:
        - name: order-db-storage
          persistentVolumeClaim:
            claimName: order-db-pvc