apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-service
  namespace: food-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: menu-service
  template:
    metadata:
      labels:
        app: menu-service
    spec:
      containers:
      - name: menu-service
        image: menu-service:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        env:
          - name: DB_HOST
            value: menu-db
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: admin
          - name: DB_PASS
            value: password
          - name: DB_NAME
            value: menudb
---
apiVersion: v1
kind: Service
metadata:
  name: menu-service
  namespace: food-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: menu-service