apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: food-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        env:
          - name: DB_HOST
            value: order-db
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: admin
          - name: DB_PASS
            value: password
          - name: DB_NAME
            value: orderdb
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: food-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: order-service
