apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: food-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: payment-service:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        env:
          - name: DB_HOST
            value: payment-db
          - name: DB_PORT
            value: "3306"
          - name: DB_USER
            value: admin
          - name: DB_PASS
            value: password
          - name: DB_NAME
            value: paymentdb
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: food-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: payment-service
