apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: food-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: user-service:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        env:
          - name: DB_HOST
            value: user-db
          - name: DB_PORT
            value: "3306"
          - name: DB_USER
            value: admin
          - name: DB_PASS
            value: password
          - name: DB_NAME
            value: userdb
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: food-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: user-service
