apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: food-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-deployment
  template:
    metadata:
      labels:
        app: order-deployment
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: order-deployment
        image: ghcr.io/felixopk/order-service:main-8912d91st
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: order-db-secret
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: order-db-secret
                key: password
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: order-db-secret
                key: host
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: order-db-secret
                key: port
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: order-db-secret
                key: database
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: food-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: order-deployment