apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: food-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-deployment
  template:
    metadata:
      labels:
        app: payment-deployment
    spec:
      containers:
        - name: payment-deployment
          image: ghcr.io/felixopk/payment-service:main-e5122cast
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: database
      imagePullSecrets:
        - name: ghcr-secret